### PR TITLE
Use MemoryStat.TotalBytesUsed instead of doing a calculation

### PR DESCRIPTION
**Pull request by benmoss**
MemoryStat.TotalBytesUsed is a new field added to Garden so that both Windows and Linux can do their own calculations

66f7613 is included so that tests pass against the latest Garden repo ; it is only relevant to this PR since we need to build against the latest Garden.

We also added the "ignored" comment to all the other MemoryStat fields in the test, not sure if that is right but we followed what appeared to be the pattern ; feel free to remove them.

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @benmoss! This is blocked on the garden API change (https://github.com/cloudfoundry-incubator/garden/pull/35) and its garden-linux (https://github.com/cloudfoundry-incubator/garden-linux/pull/44) and garden-windows implementations, right?

Thanks,
Eric

**Comment by benmoss** [comment]
@ematpl yep, sorry that we didn't make that clear.

**Comment by ematpl** [comment]
No problem, thanks for confirming! Which story implements this for garden-windows?

Thanks,
Eric

**Comment by benmoss** [comment]
https://www.pivotaltracker.com/story/show/93055226 is the story, there's not a PR right now

**Comment by benmoss** [comment]
Also we noticed that executor can't be built against the latest Garden because of `ProcessSpec`'s `Privileged` flag being removed, so now we actually are blocked from releasing our metrics endpoint until Executor is upgraded to the latest Garden.

image

**Comment by ematpl** [comment]
Thanks! Yes, we know we need to update garden in diego-release and deal with the API ∆ consequences: https://www.pivotaltracker.com/story/show/94140792

**Comment by goonzoid** [comment]
The PRs mentioned above have now been merged in Garden and Garden-Linux. Thanks for driving this @benmoss.

**Comment by ematpl** [comment]
Hi, @benmoss and @dgoddard,

These commits were rebased and pushed as https://github.com/cloudfoundry-incubator/executor/commit/c0cfb5fd9d8eeedf23f53de76ecbf01c5d54fe91, https://github.com/cloudfoundry-incubator/executor/commit/5968546d4d6b1e01fd9a595b4467925c29c5ff65, and https://github.com/cloudfoundry-incubator/executor/commit/e46e65dc605696be913d08e6a39e72d726f3e68a, and have now been bumped in diego-release. Thanks!

Best,
Eric

**Pull request closed without merging**
